USE CSE_3A_259

--1. Add two more columns City VARCHAR (20) and Pincode INT.
ALTER TABLE DEPOSIT ADD CITY VARCHAR(20),PINCODE INT

--2. Change the size of CNAME column from VARCHAR (50) to VARCHAR (35).
ALTER TABLE DEPOSIT ALTER COLUMN CNAME VARCHAR(50)

--3. Change the data type DECIMAL to INT in amount Column.
ALTER TABLE DEPOSIT ALTER COLUMN AMOUNT  INT

--4. Rename Column ActNo to ANO.
SP_RENAME 'DEPOSIT.ACTNO','ANO'

--5. Delete Column City from the DEPOSIT table.
ALTER TABLE DEPOSIT DROP  COLUMN BNAME

--6. Change name of table DEPOSIT to DEPOSIT_DETAIL.
SP_RENAME DEPOSIT , DEPOSIT_DETAIL


PART B:

--1. Rename Column ADATE to AOPENDATE OF DEPOSIT_DETAIL table.
 SP_RENAME 'DEPOSIT_DETAIL.ADATE','AOPENDATE'

--2. Delete Column AOPENDATE from the DEPOSIT_DETAIL table.
ALTER TABLE DEPOSIT_DETAIL DROP COLUMN AOPDATE

--3. Rename Column CNAME to CustomerName.
SP_RENAME 'DEPOSIT_DETAIL.CNAME','CUSTOMERNAME'

--PART C
--1. Add two more columns City VARCHAR (20) (Not null) and Backlog INT (Null).
ALTER TABLE STUDENT_DETAIL ADD CITY VARCHAR(50)NOT NULL,BACKLOG INT NULL

--2. Change the size of NAME column of student_detail from VARCHAR (25) to VARCHAR (35).

ALTER TABLE DEPOSIT_DETAIL ALTER COLUMN CNAME VARCHAR(35)

--3. Change the data type DECIMAL to INT in CPI Column.

ALTER TABLE DEPOSIT_DETAIL ALTER COLUMN CPI INT

--4. Rename Column Enrollment_No to ENO.

SP_RENAME 'DEPOSIT_DETAIL.ENROLLMENT','CUSTOMERNAME'

--5. Delete Column City from the student_detail table.

ALTER TABLE DEPOSIT_DETAIL DROP COLUMN CITY

--6. Change name of table student_detail to STUDENT_MASTER.

SP_RENAME 'DEPOSIT_DETAIL'





--DELETE
--PART A
--1.Delete all the records of DEPOSIT_DETAIL table having amount greater than and equals to 4000. 
DELETE FROM DEPOSIT_DETAIL WHERE AMOUNT >= 4000

--2. Delete all the accounts CHANDI BRANCH.
DELETE FROM DEPOSIT_DETAIL WHERE BNAME ='CHANDI'

--3. Delete all the accounts having account number (ANO) is greater than 105.
DELETE FROM DEPOSIT_DETAIL WHERE ANO>105

--4. Delete all the records of Deposit_Detail table. (Use Truncate)
TRUNCATE TABLE DEPOSIT_DETAIL

--5. Remove Deposit_Detail table. (Use Drop)
DROP TABLE DEPOSIT_DETAIL

--PART B
CREATE TABLE EMPLOYEE_MASTER(
		
		EMPNO INT,
		EMPNAME VARCHAR(50),
		JOININGDATE DATETIME,
		SALARY DECIMAL(8,2),
		CITY VARCHAR(20)
		);
INSERT INTO EMPLOYEE_MASTER(EMPNO,EMPNAME,JOININGDATE,SALARY,CITY)VALUES(101,'KEYUR','2002-01-05',12000,'RAJKOT')
INSERT INTO EMPLOYEE_MASTER(EMPNO,EMPNAME,JOININGDATE,SALARY,CITY)VALUES(102,'Hardik','2004-02-04',14000,'AHMEDABAD')
INSERT INTO EMPLOYEE_MASTER(EMPNO,EMPNAME,JOININGDATE,SALARY,CITY)VALUES(103,'Kajal','2006-03-06',15000,'BARODA')
INSERT INTO EMPLOYEE_MASTER(EMPNO,EMPNAME,JOININGDATE,SALARY,CITY)VALUES(104,'BHOOMI','2005-06-05',12500,'AHMEDABAD')
INSERT INTO EMPLOYEE_MASTER(EMPNO,EMPNAME,JOININGDATE,SALARY,CITY)VALUES(105,'HARMIT','2004-02-04',14000,'RAJKOT')
INSERT INTO EMPLOYEE_MASTER(EMPNO,EMPNAME,JOININGDATE,SALARY,CITY)VALUES(106,'MITESH','2001-09-01',5000,'JAMNAGAR')
INSERT INTO EMPLOYEE_MASTER(EMPNO,EMPNAME,JOININGDATE,SALARY,CITY)VALUES(107,'MEERA',NULL,7000,'MORBI')
INSERT INTO EMPLOYEE_MASTER(EMPNO,EMPNAME,JOININGDATE,SALARY,CITY)VALUES(108,'KISHAN','2003-02-06',10000,NULL)

SELECT * FROM EMPLOYEE_MASTER

--1. Delete all the records of Employee_MASTER table having salary greater than and equals to 14000. 
DELETE FROM EMPLOYEE_MASTER WHERE SALARY >=14000

--2. Delete all the Employees who belongs to ‘RAJKOT’ city.
DELETE FROM EMPLOYEE_MASTER WHERE CITY ='RAJKOT'

--3. Delete all the Employees who joined after 1-1-2007.
DELETE FROM EMPLOYEE_MASTER WHERE JOININGDATE<'2007-01-01'

--4. Delete the records of Employees whose joining date is null and Name is not null.
DELETE FROM EMPLOYEE_MASTER WHERE JOININGDATE IS NULL AND NAME IS NOT NULL

--5. Delete the records of Employees whose salary is 50% of 20000.
DELETE TOP 50 PERCENT FROM EMPLOYEE_MASTER WHERE SALARY>=14000

--6. Delete the records of Employees whose City Name is not empty.
DELETE FROM EMPLOYEE_MASTER WHERE CITY IS NOT NULL

--7. Delete all the records of Employee_MASTER table. (Use Truncate)
TRUNCATE TABLE EMPLOYEE_MASTER

--8. Remove Employee_MASTER table. (Use Drop)
DROP TABLE EMPLOYEE_MASTER 
SELECT * FROM EMPLOYEE_MASTER

